import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";

function App() {
  const mockedData = [
    {
      title: "Room 1",
      id: 1,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 2",
      id: 2,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 3",
      id: 3,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 4",
      id: 4,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 5",
      id: 5,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 6",
      id: 6,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 7",
      id: 7,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 8",
      id: 8,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 9",
      id: 9,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 10",
      id: 10,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 11",
      id: 11,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 12",
      id: 12,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 13",
      id: 13,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 14",
      id: 14,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 15",
      id: 15,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 16",
      id: 16,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 17",
      id: 17,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 18",
      id: 18,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 19",
      id: 19,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 20",
      id: 20,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 21",
      id: 21,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 22",
      id: 22,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 23",
      id: 23,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 24",
      id: 24,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 25",
      id: 25,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 26",
      id: 26,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 27",
      id: 27,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 28",
      id: 28,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 29",
      id: 29,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 30",
      id: 30,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 31",
      id: 31,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 32",
      id: 32,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 33",
      id: 33,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 34",
      id: 34,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 35",
      id: 35,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 36",
      id: 36,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 37",
      id: 37,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 38",
      id: 38,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 39",
      id: 39,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 40",
      id: 40,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 41",
      id: 41,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 42",
      id: 42,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 43",
      id: 43,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 44",
      id: 44,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 45",
      id: 45,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 46",
      id: 46,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 47",
      id: 47,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 48",
      id: 48,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 49",
      id: 49,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 50",
      id: 50,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 51",
      id: 51,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 52",
      id: 52,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 53",
      id: 53,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 54",
      id: 54,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 55",
      id: 55,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 56",
      id: 56,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 57",
      id: 57,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 58",
      id: 58,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 59",
      id: 59,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 60",
      id: 60,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 61",
      id: 61,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 62",
      id: 62,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 63",
      id: 63,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 64",
      id: 64,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 65",
      id: 65,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 66",
      id: 66,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 67",
      id: 67,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 68",
      id: 68,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 69",
      id: 69,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 70",
      id: 70,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 71",
      id: 71,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 72",
      id: 72,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 73",
      id: 73,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 74",
      id: 74,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 75",
      id: 75,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 76",
      id: 76,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 77",
      id: 77,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 78",
      id: 78,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 79",
      id: 79,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 80",
      id: 80,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 81",
      id: 81,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 82",
      id: 82,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 83",
      id: 83,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 84",
      id: 84,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 85",
      id: 85,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 86",
      id: 86,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 87",
      id: 87,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 88",
      id: 88,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 89",
      id: 89,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 90",
      id: 90,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 91",
      id: 91,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 92",
      id: 92,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 93",
      id: 93,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 94",
      id: 94,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 95",
      id: 95,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 96",
      id: 96,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 97",
      id: 97,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 98",
      id: 98,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 99",
      id: 99,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
    {
      title: "Room 100",
      id: 100,
      link: "/",
      city: "New York",
      address: "Calle de la esperanza",
      image: "https://placehold.co/600x400",
    },
  ];

  return (
    <main>
      <h1>Spot A Room</h1>

      <section>
        <TableContainer component={Paper}>
          <Table sx={{ minWidth: 650 }} aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell>Title</TableCell>
                <TableCell align="right">Link</TableCell>
                <TableCell align="right">City</TableCell>
                <TableCell align="right">Address</TableCell>
                <TableCell align="right">Image</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {mockedData.map((row) => (
                <TableRow
                  key={row.id}
                  sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                >
                  <TableCell component="th" scope="row">
                    {row.title}
                  </TableCell>
                  <TableCell component="th" scope="row">
                    {row.link}
                  </TableCell>
                  <TableCell align="right">{row.city}</TableCell>
                  <TableCell align="right">{row.address}</TableCell>
                  <TableCell align="right">
                    <img
                      src={row.image}
                      alt={row.title}
                      className="table-image"
                    />
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </section>
    </main>
  );
}

export default App;
